
build: prism/src/userinterface/model/*.java
	rm -rf build-cursor-test
	mkdir -p build-cursor-test
	javac -sourcepath prism/src \
	  -source 8 \
	  -target 8 \
	  -d build-cursor-test \
	  prism/src/userinterface/model/GUIParedDownEditor.java
	 cd build-cursor-test && jar cfe ../cursor-test-jdk8.jar userinterface.model.GUIParedDownEditor */*/*.class
